name: Build and check commit

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
      - name: Install modules
        run: npm ci
      - name: Run Check
        run: npm run check
      - name: Build App
        run: npm run build