name: Build and check commit

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v1
      - name: Install modules
        run: bun install
      - name: Run Check
        run: bun run check
      - name: Build App
        run: bun run build
