# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16
      - name: Install modules
        run: npm ci
      - name: Build App
        run: npm run build
      - name: Check App
        run: npm run check
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'